### ISSUE TITLE
skinnskatteberg.se

### ISSUE THREAD

**Issue by tobbe-eklov** [dotse/zonemaster-gui#118]
Hello.
If you test skinnskatteberg.se it takes hours.

/Tobbe

**Comment by sandoche2k** [comment]
Hi Tobbe,

  Thanks for your message.

  We did identify there is an issue in Zonemaster where even when certain
nameservers for a domain does not respond, Zonemaster tends to run all the
remaining tests. I have assigned this issue as priority to be solved.

  Since this is holiday period thanks for expecting a delay to having this
solved.

Sandoche.

**Comment by sandoche2k** [comment]
@vlevigneron seems to be the result of this issue : https://github.com/dotse/zonemaster-engine/issues/96

**Comment by sandoche2k** [comment]
Hi @tobbe-eklov , 

  The issue has been fixed.

**Comment by sandoche2k** [comment]
@mtoma  close ?

**Comment by mtoma** [comment]
Can be closed.

----- Original Message -----
