### ISSUE TITLE
Bug in rendering saved result

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-gui#57]
See http://zonemaster.net/test/210 - you have JSON stuff flowing the top of the page. And for some reason it looks different to me each time I render the page.

**Comment by mtoma** [comment]
Why do you need to see precisely the results of test 210?
How did you get to this test?
Those are SQL injection test results from the security audit, I can delete them from the database but rather prefer not to.
In any case, this is not a bug.

**Comment by pawal** [comment]
This is from a user report. Any user can enumerate the test identifiers. Those should not be numeric for that reason alone. Could you change it for one of our planned releases?

**Comment by mtoma** [comment]
The problem here is that the code assumes numeric IDs of tests with new tests having higher ID than older tests. So I can change this to let say a millisecond epoch easily but the only thing that would change would be that a user willing to enumerate the results would send about 1000000 times more traffic. I don't want to see this on the server.
We should first decide if it is any kind of problem if a user enumerates all the results from the database.
From my point of view it is not.
It the user enumerates the database he is not in a normal use-case of the service and should not expect us to handle issues on old tests that are impossible to access otherwise than by enumerating the database and thus are not the standard scenario.
If the user tells me "I want to test the domain test.fr" and I see strange results in the history then I will delete the test number 210 from the database.
If we want to change the IDs to something non numeric this will require some work and a potentially not a little work as this ID is used in the same way in all 4 database backends.

**Comment by pawal** [comment]
We decided to remove any tests that might cause a user to see a broken web interface.

**Comment by mtoma** [comment]
All test results with id<1000 were archived and deleted from the main table.
